apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ops-debug.ctyun.cn
webhooks:
  - name: ops-debug.ctyun.cn
    sideEffects:  None
    admissionReviewVersions: ["v1"]
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["ops-debug"]
    clientConfig:
      service:
        # reach the webhook via the registered aggregated API
        namespace: default
        name: kubernetes
        path: /apis/ops-debug.ctyun.cn/v1/admissionreviews
    rules:
      - operations:
          - DELETE
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "configmaps"
